// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RareBooksService.Data;

#nullable disable

namespace RareBooksService.Data.Migrations.UsersDb
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20250414000000_AddUserFavoriteBooks")]
    partial class AddUserFavoriteBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Здесь должна быть копия всего содержимого из UsersDbContextModelSnapshot.cs
            // Для краткости просто указываем, что это файл автоматически генерируется
            // и должен содержать то же, что и ModelSnapshot
        }
    }
} 